//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankatb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bankatb()
        {
            this.bilettb = new HashSet<bilettb>();
        }
    
        public short bankaid { get; set; }
        public Nullable<decimal> hesapno { get; set; }
        public Nullable<System.DateTime> sonkullanmatarih { get; set; }
        public Nullable<decimal> guvenlikkodu { get; set; }
        public Nullable<short> ibanno { get; set; }
        public string bankaadi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilettb> bilettb { get; set; }
    }
}
