//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilettb
    {
        public short biletid { get; set; }
        public Nullable<System.DateTime> kayittarih { get; set; }
        public Nullable<short> uyeid { get; set; }
        public Nullable<System.DateTime> biletkayittarih { get; set; }
        public Nullable<short> filmid { get; set; }
        public Nullable<short> sahneid { get; set; }
        public Nullable<short> koltukid { get; set; }
        public Nullable<short> biletdurumid { get; set; }
        public Nullable<short> bankaid { get; set; }
        public Nullable<short> gorevliid { get; set; }
    
        public virtual bankatb bankatb { get; set; }
        public virtual biletdurumtb biletdurumtb { get; set; }
        public virtual gorevlilertb gorevlilertb { get; set; }
        public virtual koltuktb koltuktb { get; set; }
        public virtual salon salon { get; set; }
        public virtual uyetb uyetb { get; set; }
    }
}
