//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmtb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public filmtb()
        {
            this.yorumtb = new HashSet<yorumtb>();
        }
    
        public short filmid { get; set; }
        public string filmadi { get; set; }
        public Nullable<System.DateTime> filmsüre { get; set; }
        public Nullable<short> filmtürü { get; set; }
        public string filmyonetmeni { get; set; }
        public string filmoyunculari { get; set; }
        public string filmaciklama { get; set; }
        public string filmfoto { get; set; }
        public Nullable<short> seansid { get; set; }
        public Nullable<short> salon1 { get; set; }
        public Nullable<short> salon2 { get; set; }
    
        public virtual filmturutb filmturutb { get; set; }
        public virtual salon salon { get; set; }
        public virtual salon salon3 { get; set; }
        public virtual seanstb seanstb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorumtb> yorumtb { get; set; }
    }
}
