//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisimtb
    {
        public short iletisimid { get; set; }
        public string adres { get; set; }
        public Nullable<decimal> telefon { get; set; }
        public string mail { get; set; }
    }
}
