//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class koltuktb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public koltuktb()
        {
            this.bilettb = new HashSet<bilettb>();
        }
    
        public short koltukid { get; set; }
        public Nullable<short> blokid { get; set; }
        public Nullable<short> sahneid { get; set; }
        public Nullable<short> koltuknumarasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilettb> bilettb { get; set; }
        public virtual bloktb bloktb { get; set; }
        public virtual salon salon { get; set; }
    }
}
