//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajkututb
    {
        public short mesajid { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }
        public Nullable<short> uyeid { get; set; }
        public Nullable<System.DateTime> mesajtarihi { get; set; }
    
        public virtual uyetb uyetb { get; set; }
    }
}
