//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SINEMADBEntities : DbContext
    {
        public SINEMADBEntities()
            : base("name=SINEMADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bankatb> bankatb { get; set; }
        public virtual DbSet<biletdurumtb> biletdurumtb { get; set; }
        public virtual DbSet<bilettb> bilettb { get; set; }
        public virtual DbSet<bloktb> bloktb { get; set; }
        public virtual DbSet<filmtb> filmtb { get; set; }
        public virtual DbSet<filmturutb> filmturutb { get; set; }
        public virtual DbSet<fiyat> fiyat { get; set; }
        public virtual DbSet<gorevlilertb> gorevlilertb { get; set; }
        public virtual DbSet<iletisimtb> iletisimtb { get; set; }
        public virtual DbSet<koltuktb> koltuktb { get; set; }
        public virtual DbSet<kullanicituru> kullanicituru { get; set; }
        public virtual DbSet<mesajkututb> mesajkututb { get; set; }
        public virtual DbSet<salon> salon { get; set; }
        public virtual DbSet<seanstb> seanstb { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<uyetb> uyetb { get; set; }
        public virtual DbSet<yorumtb> yorumtb { get; set; }
    }
}
