//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seanstb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seanstb()
        {
            this.filmtb = new HashSet<filmtb>();
        }
    
        public short seansid { get; set; }
        public Nullable<System.DateTime> filmyayintarihi { get; set; }
        public Nullable<System.DateTime> filmsonyayintarihi { get; set; }
        public Nullable<System.TimeSpan> saat1 { get; set; }
        public Nullable<System.TimeSpan> saat2 { get; set; }
        public Nullable<System.TimeSpan> saat3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filmtb> filmtb { get; set; }
    }
}
