//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyetb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyetb()
        {
            this.bilettb = new HashSet<bilettb>();
            this.mesajkututb = new HashSet<mesajkututb>();
            this.yorumtb = new HashSet<yorumtb>();
        }
    
        public short uyeid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string mail { get; set; }
        public Nullable<decimal> uyetelefon { get; set; }
        public string sifre { get; set; }
        public Nullable<short> kullaniciturid { get; set; }
        public Nullable<decimal> tcno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilettb> bilettb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesajkututb> mesajkututb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorumtb> yorumtb { get; set; }
        public object Uye { get; internal set; }
    }
}
