//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINEMAWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorumtb
    {
        public short yorumid { get; set; }
        public string yorum { get; set; }
        public Nullable<short> uyeid { get; set; }
        public Nullable<System.DateTime> yorumtarih { get; set; }
        public Nullable<short> filmid { get; set; }
    
        public virtual filmtb filmtb { get; set; }
        public virtual uyetb uyetb { get; set; }
    }
}
