//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBTiyatro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int BiletID { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string BiletNo { get; set; }
        public Nullable<int> OyunID { get; set; }
        public Nullable<int> SahneID { get; set; }
        public Nullable<int> FiyatID { get; set; }
        public Nullable<int> KoltukID { get; set; }
        public int BankaID { get; set; }
        public Nullable<int> BiletDurumID { get; set; }
    
        public virtual Banka Banka { get; set; }
        public virtual BiletDurum BiletDurum { get; set; }
        public virtual Fiyat Fiyat { get; set; }
        public virtual Koltuk Koltuk { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Oyunlar Oyunlar { get; set; }
        public virtual Sahneler Sahneler { get; set; }
    }
}
