//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBTiyatro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Bilet = new HashSet<Bilet>();
            this.MesajKutusu = new HashSet<MesajKutusu>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int KullaniciID { get; set; }

        [Required(ErrorMessage = "Hatali")]
        public string Sifre { get; set; }

        [Required(ErrorMessage = "Hatali")]
        public string SifreTekrari { get; set; }

        [Required(ErrorMessage = "Hatali")]
        public string KullaniciSoyadi { get; set; }

        [Required(ErrorMessage = "Hatali")]
        public string Telefon { get; set; }

        //[DataType(DataType.EmailAddress,ErrorMessage ="Hatali")]
        [StringLength(50,ErrorMessage ="{0} alaný en fazla {1} karakter uzunluðunda olmalýdýr!!")]
        [Required(ErrorMessage = "Hatali")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                           @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                           @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                           ErrorMessage = "Email adresi geçersiz")]
        public string EPosta { get; set; }

        [Required(ErrorMessage = "Hatali")]
        public string KullaniciAdi { get; set; }

        public Nullable<int> MesajID { get; set; }
        public string UyeKodu { get; set; }
        public string Onay { get; set; }
        public Nullable<int> RolID { get; set; }
        [StringLength(11,ErrorMessage ="kontrol ediniz",MinimumLength =11)]
        public string TC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Iletisim Iletisim { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajKutusu> MesajKutusu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
