//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBTiyatro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OyunTakvimi
    {
        public int TakvimId { get; set; }
        public string Yil { get; set; }
        public string Aylar { get; set; }
        public Nullable<int> OyunNo { get; set; }
        public string Gunler { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
        public Nullable<int> SahneNo { get; set; }
    
        public virtual Oyunlar Oyunlar { get; set; }
        public virtual Sahneler Sahneler { get; set; }
    }
}
