//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBTiyatro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumId { get; set; }
        public string Konu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> OyunID { get; set; }
        public Nullable<int> ResimID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Oyunlar Oyunlar { get; set; }
    }
}
